default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: bullshitmeter_development
test:
  <<: *default
  database: bullshitmeter_test
production:
  <<: *default
  database: bullshitmeter_production
